# Generated by Django 5.2.9 on 2025-12-02 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CyclePhaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_id', models.IntegerField(help_text='Cycle number identifier')),
                ('phase_name', models.CharField(choices=[('Menstrual', 'Menstrual'), ('Follicular', 'Follicular'), ('Ovulatory', 'Ovulatory'), ('Luteal', 'Luteal')], help_text='Current menstrual cycle phase', max_length=50)),
                ('pace', models.DecimalField(decimal_places=2, help_text='Running pace in minutes per kilometer', max_digits=5)),
                ('motivation_level', models.IntegerField(help_text='Motivation level from 1 to 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                # ('entry_timestamp', models.DateTimeField(help_text='When this entry was recorded')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created in the database')),
            ],
            options={
                'verbose_name': 'Cycle Phase Entry',
                'verbose_name_plural': 'Cycle Phase Entries',
                'db_table': 'cycle_phase_entries',
                # 'ordering': ['-entry_timestamp'],
                'indexes': [models.Index(fields=['cycle_id', 'phase_name'], name='idx_cycle_phase'), models.Index(fields=['phase_name', 'entry_timestamp'], name='idx_phase_timestamp')],
            },
        ),
    ]
