# Generated by Django 5.2.9 on 2025-12-03 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_cycle_length', models.IntegerField(default=28)),
                ('last_period_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RunEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('pace', models.DecimalField(decimal_places=2, help_text='Minutes per km', max_digits=5)),
                ('distance', models.DecimalField(decimal_places=2, help_text='Kilometers', max_digits=6)),
                ('motivation_level', models.IntegerField()),
                ('cycle_phase', models.CharField(max_length=50)),
                ('cycle_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'cycle_id'], name='api_runentr_user_id_799f81_idx'), models.Index(fields=['user', 'cycle_phase'], name='api_runentr_user_id_3dd58f_idx')],
            },
        ),
    ]
