# Generated by Django 5.2.10 on 2026-02-19 12:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_last_period_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trackable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('severity', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.symptom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'date'], name='api_symptom_user_id_cdf4ac_idx')],
                'unique_together': {('user', 'symptom', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TrackableLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('value_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trackable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.trackable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackable_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'date'], name='api_trackab_user_id_850836_idx')],
                'unique_together': {('user', 'trackable', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserSymptom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.symptom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'symptom')},
            },
        ),
        migrations.CreateModel(
            name='UserTrackable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trackable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trackable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'trackable')},
            },
        ),
    ]
