# Generated by Django 5.2.9 on 2025-12-03 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_runentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cyclephaseentry',
            name='idx_cycle_phase',
        ),
        migrations.RemoveIndex(
            model_name='cyclephaseentry',
            name='idx_phase_timestamp',
        ),
        migrations.RenameIndex(
            model_name='runentry',
            new_name='idx_user_cycle',
            old_name='api_runentr_user_id_799f81_idx',
        ),
        migrations.RenameIndex(
            model_name='runentry',
            new_name='idx_user_phase',
            old_name='api_runentr_user_id_3dd58f_idx',
        ),
        migrations.AddField(
            model_name='cyclephaseentry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cycle_phase_entries', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cyclephaseentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='runentry',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='runentry',
            name='pace',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='runentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cyclephaseentry',
            index=models.Index(fields=['user', 'cycle_id', 'phase_name'], name='idx_user_cycle_phase'),
        ),
        migrations.AddIndex(
            model_name='cyclephaseentry',
            index=models.Index(fields=['user', 'phase_name'], name='idx_user_phase_timestamp'),
        ),
    ]
