# Generated by Django 5.2.9 on 2025-12-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_cyclephaseentry_idx_cycle_phase_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cyclephaseentry',
            name='idx_user_phase_timestamp',
        ),
    ]
