# Generated by Django 5.2.10 on 2026-03-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cycle_cyclesamplelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyclesamplelog',
            name='day_of_cycle',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
