# Generated by Django 5.2.9 on 2025-12-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_cyclephaseentry_idx_user_phase_timestamp'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='runentry',
            name='idx_user_cycle',
        ),
        migrations.RemoveIndex(
            model_name='runentry',
            name='idx_user_phase',
        ),
    ]
