# Generated by Django 5.2.10 on 2026-03-07 15:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cyclesamplelog_day_of_cycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('menstrual', 'Menstrual'), ('follicular', 'Follicular'), ('ovulatory', 'Ovulatory'), ('luteal', 'Luteal'), ('any', 'Any Phase')], max_length=20)),
                ('cycle_day_min', models.IntegerField(blank=True, null=True)),
                ('cycle_day_max', models.IntegerField(blank=True, null=True)),
                ('condition_type', models.CharField(choices=[('none', 'No Condition (Phase Only)'), ('symptom', 'Symptom Logged Today'), ('trackable_numeric', 'Trackable — Numeric Threshold'), ('trackable_baseline', 'Trackable — vs Personal Baseline')], default='none', max_length=30)),
                ('condition_key', models.CharField(blank=True, max_length=120)),
                ('condition_operator', models.CharField(blank=True, choices=[('gte', '>='), ('lte', '<='), ('eq', '=='), ('above_baseline', 'Above Personal Baseline'), ('below_baseline', 'Below Personal Baseline')], max_length=20)),
                ('condition_value', models.FloatField(blank=True, null=True)),
                ('advice_category', models.CharField(choices=[('training', 'Training'), ('recovery', 'Recovery'), ('nutrition', 'Nutrition'), ('mindset', 'Mindset')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('advice_text', models.TextField()),
                ('priority', models.IntegerField(default=5)),
                ('is_generic', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='DailyAdviceCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('advice', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advice_cache', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
