# Generated by Django 5.2.10 on 2026-03-16 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_advicerule_dailyadvicecache'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('Menstrual', 'Menstrual'), ('Follicular', 'Follicular'), ('Ovulatory', 'Ovulatory'), ('Luteal', 'Luteal')], max_length=20)),
                ('day_of_cycle', models.IntegerField()),
                ('phase_start_date', models.DateField()),
                ('predicted_next_phase_date', models.DateField()),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_phases', to='api.cycle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_phase', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
