# Generated by Django 5.2.10 on 2026-03-16 18:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_activephase'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('race_type', models.CharField(choices=[('5k', '5K'), ('10k', '10K'), ('half_marathon', 'Half Marathon'), ('marathon', 'Marathon'), ('fun', 'Run for Fun')], max_length=20)),
                ('race_date', models.DateField(blank=True, null=True)),
                ('goal_time', models.DurationField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescribedSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('baseline_5k', 'Baseline 5K'), ('easy', 'Easy Run'), ('moderate', 'Moderate Run'), ('tempo', 'Tempo Run'), ('long_run', 'Long Run'), ('rest', 'Rest Day')], max_length=20)),
                ('cycle_phase', models.CharField(choices=[('Menstruation', 'Menstruation'), ('Follicular', 'Follicular'), ('Ovulatory', 'Ovulatory'), ('Luteal', 'Luteal')], max_length=20)),
                ('prescribed_date', models.DateField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_session', to='api.runentry')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_sessions', to='api.cycle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_sessions', to=settings.AUTH_USER_MODEL)),
                ('race_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_sessions', to='api.racegoal')),
            ],
            options={
                'ordering': ['-prescribed_date'],
                'indexes': [models.Index(fields=['user', 'status'], name='idx_prescribed_user_status'), models.Index(fields=['user', 'cycle_phase'], name='idx_prescribed_user_phase')],
            },
        ),
    ]
