# Generated by Django 5.2.10 on 2026-03-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_racegoal_prescribedsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='racegoal',
            name='race_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
