# Generated by Django 5.2.10 on 2026-03-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_racegoal_race_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racegoal',
            name='race_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
