# Generated by Django 5.2.10 on 2026-03-23 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_racegoal_race_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribedsession',
            name='race_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_sessions', to='api.racegoal'),
        ),
    ]
