# Generated by Django 5.2.10 on 2026-03-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_prescribedsession_race_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='runentry',
            name='exertion_level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
