# Generated by Django 5.2.10 on 2026-03-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_runentry_exertion_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='runentry',
            name='baseline_phase',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='runentry',
            name='is_baseline',
            field=models.BooleanField(default=False),
        ),
    ]
