# Generated by Django 5.2.10 on 2026-03-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_runentry_baseline_phase_runentry_is_baseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='runentry',
            name='is_prescribed',
            field=models.BooleanField(default=False),
        ),
    ]
